#version: '3.8'

services:
  # 1. MLflow Tracking
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: mlflow-server
    user: "root"
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    working_dir: /app
    command: mlflow ui --host 0.0.0.0 --port 5000
    networks:
      - wav2vec2-net

  # 2. Training Job
  wav2vec2-train:
    build: .
    image: wav2vec2-vi:latest
    container_name: wav2vec2-train
    depends_on:
      - mlflow
    volumes:
      - ./data_train_70.6:/app/data_train_70.6
      - ./models:/app/models
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: >
      python train_wav2vec2.py
      --extracted_dir /app/data_train_70.6
      --meta_csv /app/data_train_70.6/metadata.csv
      --output_dir /app/models/wav2vec2-finetuned
      --num_train_epochs 35
      --learning_rate 1e-5
      --per_device_train_batch_size 2  
      --gradient_accumulation_steps 12
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - wav2vec2-net

  # 3. Evaluation Job
  wav2vec2-eval:
    build: .
    image: wav2vec2-vi:latest
    container_name: wav2vec2-eval
    depends_on:
      - mlflow
    volumes:
      - ./data_train_70.6:/app/data_train_70.6
      - ./person_name_500:/app/person_name_500
      - ./models:/app/models
      - ./outputs:/app/outputs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: >
      python eval_wav2vec2.py
      --model_dir /app/models/wav2vec2-finetuned
      --local_weights /app/models/wav2vec2-finetuned/model.safetensors
      --wav_dir /app/person_name_500
      --out_save_dir /app/outputs
      --run_postprocess
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - wav2vec2-net

  # 4. FastAPI Inference Server (API Hàng Real)
  wav2vec2-api:
    build: .
    container_name: wav2vec2-api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    volumes:
      - ./models:/app/models
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    networks:
      - wav2vec2-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # 5. Streamlit Frontend UI
  frontend-ui:
    build: .
    container_name: frontend-ui
    ports:
      - "8501:8501"
    depends_on:
      - wav2vec2-api
    command: streamlit run frontend.py --server.port=8501 --server.address=0.0.0.0
    networks:
      - wav2vec2-net

  # 6. Prometheus (Gom Data)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - wav2vec2-net
    depends_on:
      - wav2vec2-api

  # 7. Grafana (Vẽ Biểu Đồ Thật)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - wav2vec2-net
    depends_on:
      - prometheus

networks:
  wav2vec2-net:
    driver: bridge

volumes:
  data:
  models:
  outputs:
  mlruns: