apiVersion: apps/v1
kind: Deployment
metadata:
  name: wav2vec2-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wav2vec2-asr
  template:
    metadata:
      labels:
        app: wav2vec2-asr
    spec:
      containers:
      - name: asr-container
        image: ghcr.io/manhmanh39/mlops_speed_to_text:sha-92393fe
        imagePullPolicy: IfNotPresent
        command: ["python"]
        args: ["app.py"]
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://192.168.49.1:5000"
        - name: DATA_PATH
          value: "/content/data_train_70.6/metadata.csv"
        - name: HF_HOME
          value: "/content/data_train_70.6/.cache"
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "2"
        ports:
        - containerPort: 8000
        
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
        
        volumeMounts:
        - name: data-storage
          mountPath: /content/data_train_70.6
      
      volumes:
      - name: data-storage
        hostPath:
          path: /home/embiekhochiu/manh_code/mlops_speed_to_text/data_train_70.6