apiVersion: v1
kind: Service
metadata:
  name: wav2vec2-service
spec:
  type: NodePort 
  selector:
    app: wav2vec2-asr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080